disabled_rules:
  - type_name
  - identifier_name
  - switch_case_alignment
  - cyclomatic_complexity # Too many false alarms for enum conversion switch statements
  - redundant_optional_initialization
  - closure_parameter_position
  - opening_brace
  - nesting # Sometimes it just makes sense to nest 2 levels deep
  - trailing_comma # Conflicts with swift-format
  - file_length
  - force_cast # Required a lot in backend implementations

line_length: 140
type_body_length: 400

included:
  - Sources
  - Examples
excluded:
  - Sources/SwiftCrossUI/Builders/ViewBuilder.swift
  - Sources/SwiftCrossUI/Builders/TableRowBuilder.swift
  - Sources/SwiftCrossUI/Views/TupleView.swift
  - Sources/SwiftCrossUI/Views/TupleViewChildren.swift
  - Sources/Gtk/Generated
  - Examples/.build
