format_version = 2

[apps.ControlsExample]
identifier = 'dev.stackotter.ControlsExample'
product = 'ControlsExample'
version = '0.1.0'

[apps.CounterExample]
identifier = 'dev.stackotter.CounterExample'
product = 'CounterExample'
version = '0.1.0'

[apps.RandomNumberGeneratorExample]
identifier = 'dev.stackotter.RandomNumberGeneratorE'
product = 'RandomNumberGeneratorE'
version = '0.1.0'

[apps.WindowingExample]
identifier = 'dev.stackotter.WindowingExample'
product = 'WindowingExample'
version = '0.1.0'

[apps.GreetingGeneratorExample]
identifier = 'dev.stackotter.GreetingGeneratorExamp'
product = 'GreetingGeneratorExamp'
version = '0.1.0'

[apps.NavigationExample]
identifier = 'dev.stackotter.NavigationExample'
product = 'NavigationExample'
version = '0.1.0'

[apps.SplitExample]
identifier = 'dev.stackotter.SplitExample'
product = 'SplitExample'
version = '0.1.0'

[apps.SpreadsheetExample]
identifier = 'dev.stackotter.SpreadsheetExample'
product = 'SpreadsheetExample'
version = '0.1.0'

[apps.StressTestExample]
identifier = 'dev.stackotter.StressTestExample'
product = 'StressTestExample'
version = '0.1.0'
